# Site settings
title: Thomas Schühly
description: My Portfolio
baseurl: "/" 
url: "thaiminater.github.io/DHBW_Scrape/" # 

# User settings
username: Thomas Schühly
email: thomas.schuehly@outlook.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
